env:
  global:
    - CC_TEST_REPORTER_ID=04e5974a271ab82f2e8d5fd1ae1ca51b1e74878c1e73a069d75d8149cc4d4cb4
language: ruby
rvm:
  - 2.6.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT